version: '3'
services:
  site:
    container_name: personal_website
    command: jekyll serve
    image: jekyll/jekyll:latest
    volumes:
      - ./:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
