# site settings
title: Justin Schellenberg
subtitle:
email: jrschellenberg@gmail.com
description: Winnipeg Located Web Designer / Developer / Entrepreneur


# build settings
markdown: kramdown

# Exclude from processing (not moved to `serve/`)
exclude:
  - uploads
  - images

# Make sure the `_site/assets/` is not trashed (webpack output)
keep_files:
  - images
  - stylesheets
  - js
  - files
  - uploads

